### ISSUE TITLE
Strava API access fails with list division failure

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/geo-activity-playground#101]
I just updated to the newest github commit and get the following error with Strava API import

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\__main__.py", line 97, in main
    options.func(options)
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\__main__.py", line 71, in <lambda>
    make_activity_repository(options.basedir, options.skip_strava),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\__main__.py", line 114, in make_activity_repository
    import_from_strava_api(repository)
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\importers\strava_api.py", line 96, in import_from_strava_api
    while try_import_strava(repository):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\importers\strava_api.py", line 141, in try_import_strava
    time_series = download_strava_time_series(activity.id, client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\importers\strava_api.py", line 194, in download_strava_time_series
    columns["distance_km"] = streams["distance"].data / 1000
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for /: 'list' and 'int'
```

_Originally posted by @Oi-sin in https://github.com/martin-ueding/geo-activity-playground/issues/88#issuecomment-1926316084_

**Comment by martin-ueding** [comment]
I see, the `streams["distance"].data` is just a mere Python `list[float]`. I've now wrapped it in a Pandas Series, it should work again with the next version.

**Comment by martin-ueding** [comment]
Version 0.20.0 is released you can update and try it out. If the issue persists, please reopen this ticket.
