### ISSUE TITLE
Some activities from the calendar just cannot be opened in activity view

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/geo-activity-playground#105]
I tried to open some activities from the calendar and it just didn't work:

```
2024-03-03 08:34:02 geo_activity_playground.webui.app ERROR Exception on /activity/3148244765964603892 [GET]
Traceback (most recent call last):
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib64/python3.9/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2606, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2630, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 3145947796808355243

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/webui/app.py", line 35, in activity
    "activity.html.j2", **activity_controller.render_activity(int(id))
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/webui/activity_controller.py", line 40, in render_activity
    similar_activites = {
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/webui/activity_controller.py", line 41, in <dictcomp>
    distance: [
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/webui/activity_controller.py", line 42, in <listcomp>
    self._repository.get_activity_by_id(activity_id)
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/core/activities.py", line 129, in get_activity_by_id
    activity = self.meta.loc[id]
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib64/python3.9/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib64/python3.9/site-packages/pandas/core/indexing.py", line 1431, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib64/python3.9/site-packages/pandas/core/indexing.py", line 1381, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib64/python3.9/site-packages/pandas/core/generic.py", line 4298, in xs
    loc = index.get_loc(key)
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib64/python3.9/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 3145947796808355243
```

I am not sure what the issue is, perhaps there is some integer overflow or something.

**Comment by martin-ueding** [comment]
This happens when there are similar activities that have vanished. Fixed in version > 0.20.0.
