### ISSUE TITLE
Import error from Strava archive

### ISSUE THREAD

**Issue by Oi-sin** [martin-ueding/geo-activity-playground#112]
I upgraded my local repository to the latest version 0.22 from origin/master. After this I got errors upon downloading the latest few activities from strava. Thus I decided to take a brand new Strava archive and to clear the cache folder for a complete new data setup. Now I get the following error during import from the Strava archive:

```
2024-06-17 08:24:54 geo_activity_playground.core.cache_migrations INFO Apply cache migration if needed …
2024-06-17 08:24:54 geo_activity_playground.core.cache_migrations INFO Applying cache migration delete_activities_per_tile …
2024-06-17 08:24:54 geo_activity_playground.core.cache_migrations INFO Applying cache migration reset_time_series_embellishment …
2024-06-17 08:24:54 geo_activity_playground.core.cache_migrations INFO Applying cache migration delete_tile_visits …
2024-06-17 08:24:54 geo_activity_playground.core.cache_migrations INFO Applying cache migration delete_heatmap_cache …
2024-06-17 08:24:54 geo_activity_playground.core.cache_migrations INFO Applying cache migration delete_activity_metadata …
2024-06-17 08:24:54 geo_activity_playground.core.cache_migrations INFO Applying cache migration delete_activity_metadata …
2024-06-17 08:24:54 geo_activity_playground.core.cache_migrations INFO Applying cache migration convert_distances_to_km …
Convert m to km: 0it [00:00, ?it/s]
2024-06-17 08:24:54 geo_activity_playground.core.cache_migrations INFO Applying cache migration delete_activity_metadata …
2024-06-17 08:24:54 geo_activity_playground.core.cache_migrations INFO Applying cache migration delete_tile_visits …
2024-06-17 08:24:54 geo_activity_playground.core.cache_migrations INFO Applying cache migration delete_heatmap_cache …
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\__main__.py", line 93, in main
    options.func(options)
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\__main__.py", line 67, in <lambda>
    *make_activity_repository(options.basedir, options.skip_strava),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\__main__.py", line 112, in make_activity_repository
    scan_for_activities(repository, tile_visit_accessor, config, skip_strava)
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\webui\upload_controller.py", line 94, in scan_for_activities
    import_from_strava_checkout(repository)
  File "C:\Users\<user>\geo-activity-playground\geo_activity_playground\importers\strava_checkout.py", line 136, in import_from_strava_checkout
    activities.columns = EXPECTED_COLUMNS
    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\pypoetry\Cache\virtualenvs\geo-activity-playground-cxaaepob-py3.12\Lib\site-packages\pandas\core\generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\<user>\AppData\Local\pypoetry\Cache\virtualenvs\geo-activity-playground-cxaaepob-py3.12\Lib\site-packages\pandas\core\generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\<user>\AppData\Local\pypoetry\Cache\virtualenvs\geo-activity-playground-cxaaepob-py3.12\Lib\site-packages\pandas\core\internals\managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "C:\Users\<user>\AppData\Local\pypoetry\Cache\virtualenvs\geo-activity-playground-cxaaepob-py3.12\Lib\site-packages\pandas\core\internals\base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 92 elements, new values have 87 elements
```

Any hints on what might be wrong? Do you need more information?

**Comment by Oi-sin** [comment]
This is the error message I get now:

```
2024-06-24 07:41:05 geo_activity_playground.importers.strava_checkout ERROR You are trying to import a Strava checkout where the `activities.csv` contains German column headers. In order to import this, we need to map these to the English ones. Unfortunately Strava has changed the number of columns. Your file has 92 but we expect 87. This means that the program needs to be updated to match the new Strava export format. Please go to https://github.com/martin-ueding/geo-activity-playground/issues and open a new issue and share the following output in the ticket:
Index(['Aktivitäts-ID', 'Aktivitätsdatum', 'Name der Aktivität',
       'Aktivitätsart', 'Aktivitätsbeschreibung', 'Verstrichene Zeit',
       'Distanz', 'Max. Herzfrequenz', 'Relative Leistung', 'Pendeln',
       'Hinweis zur Privatsphäre für Aktivitäten', 'Aktivitätsausrüstung',
       'Dateiname', 'Sportlergewicht', 'Fahrradgewicht', 'Verstrichene Zeit.1',
       'Bewegungszeit', 'Distanz.1', 'Höchstgeschw.',
       'Durchschnittliche Geschwindigkeit', 'Höhenzunahme', 'Höhenunterschied',
       'Min. Höhe', 'Max. Höhe', 'Max. Steigung', 'Durchschnittliche Steigung',
       'Durchschnittliche positive Steigung',
       'Durchschnittliche negative Steigung', 'Max. Tritt-/Schrittfrequenz',
       'Durchschnittliche Trittfrequenz', 'Max. Herzfrequenz.1',
       'Durchschnittliche Herzfrequenz', 'Max. Watt', 'Durchschnittliche Watt',
       'Kalorien', 'Max. Temperatur', 'Durchschnittliche Temperatur',
       'Relative Leistung.1', 'Gesamtarbeit', 'Anzahl Läufe', 'Bergaufzeit',
       'Bergabzeit', 'Andere Zeit', 'Gefühlte Anstrengung', 'Art', 'Startzeit',
       'Gewichtete durchschnittliche Leistung', 'Leistungszahl',
       'Gefühlte Anstrengung verwenden', 'Gefühlte relative Leistung',
       'Pendeln.1', 'Insgesamt gestemmtes Gewicht', 'Von Upload',
       'Auf Steigung angepasste Distanz', 'Wetterbeobachtungszeit',
       'Wetterlage', 'Wetter: Temperatur', 'Scheinbare Temperatur', 'Taupunkt',
       'Luftfeuchtigkeit', 'Wetter: Druck', 'Windgeschwindigkeit', 'Windböe',
       'Windrichtung', 'Niederschlagsintensität', 'Sonnenaufgangszeit',
       'Sonnenuntergangszeit', 'Mondphase', 'Fahrrad', 'Ausrüstung',
       'Niederschlagswahrscheinlichkeit', 'Niederschlagsart', 'Wolkendecke',
       'Wetter: Sichtbarkeit', 'UV-Index', 'Wetter: Ozon', 'Sprunganzahl',
       'Schwierigkeit insgesamt', 'Durchschnittlicher Flow', 'Markiert',
       'Durchschnittsgeschwindigkeit im Aufzeichnungszeitraum',
       'Auf Schotter zurückgelegte Distanz', 'Neu getestete Distanz',
       'Neu getestete Schotterdistanz', 'Aktivitätsanzahl',
       'Schritte insgesamt', 'Eingesparte CO₂-Emissionen', 'Pool-Länge',
       'Trainingsbelastung', 'Intensität',
       'Durchschnittliches auf Steigung angepasstes Tempo', 'Medien'],
      dtype='object')
Aktivitäts-ID                                          int64
Aktivitätsdatum                                       object
Name der Aktivität                                    object
Aktivitätsart                                         object
Aktivitätsbeschreibung                                object
                                                      ...
Pool-Länge                                           float64
Trainingsbelastung                                   float64
Intensität                                           float64
Durchschnittliches auf Steigung angepasstes Tempo     object
Medien                                                object
Length: 92, dtype: object
```

**Comment by p3dda** [comment]
The format has changed again to now 94 columns. 
I have reported this in #131 (did not check if there is already a corresponding issue - sorry) and generated PR #132 which adds the new columns

**Comment by martin-ueding** [comment]
With these changes it should be fixed in 0.26.0. The version 0.25.0 has a different bug, #138, but that's fixed already.

**Comment by eifelkiwi** [comment]
I also get an import error with 0.26.0.
the activities.csv from the zip file shows 94 columns.

In the cases, where the "Activity Description" contains a line break, there is a very strange break in the csv as well and the entry spans over two or more lines, not aligning with the "traditional csv structure"....
![image](https://github.com/user-attachments/assets/596db820-6883-49ba-94e3-40228361fc62)
[2024-08-07_import-error.txt](https://github.com/user-attachments/files/16532910/2024-08-07_import-error.txt)

**Comment by eifelkiwi** [comment]
I was able to find one condition that crashes the import:
Any activity that has no actual GPS data such as Pool Swimming. These activities have distance as a string (e.g. "2,000" for 2 km) and throw the following error message when importing:

`Detect deleted activities: 0it [00:00, ?it/s]
Parse activity metadata: 0it [00:00, ?it/s]
Collate activity metadata: 0it [00:00, ?it/s]
Import from Strava export: 100%|███████████████████████████████████████████████████████| 23/23 [00:08<00:00,  2.80it/s]
Enrich new activity data:  35%|███████████████████▊                                     | 8/23 [00:00<00:00, 20.82it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 116, in <module>
    main()
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 92, in main
    options.func(options)
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 66, in <lambda>
    *make_activity_repository(options.basedir, options.skip_strava),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 110, in make_activity_repository
    scan_for_activities(repository, tile_visit_accessor, config, skip_strava)
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\webui\upload\controller.py", line 105, in scan_for_activities
    enrich_activities(config.get("kind", {}))
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\core\enrichment.py", line 60, in enrich_activities
    time_series = pd.read_parquet(extracted_time_series_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pandas\io\parquet.py", line 667, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pandas\io\parquet.py", line 267, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pandas\io\parquet.py", line 140, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pandas\io\common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Cache\\Activity\\Extracted\\Time Series\\12037268733.parquet'

D:\Dokumente\GeoPlayground>pause
Drücken Sie eine beliebige Taste . . .`

**Comment by eifelkiwi** [comment]
And another thing:

When importing gpx files, if the activity is still in a activityname.gpx.gz there is an error "Filename". Manually changing the activities.csv and removing the .gz from the filename works.

And some of the files don't get extracted to \Cache\Extracted\Time Series and then the loader crashes again.

**Comment by martin-ueding** [comment]
I created separate tickets for each issue. I think the original issue here was a change in the column names. That should be fixed by now.
