### ISSUE TITLE
Strava Import Error due to RateLimit 

### ISSUE THREAD

**Issue by p3dda** [martin-ueding/geo-activity-playground#119]
Hi,

it seems the Strava API Rate Limit is not always handled correctly. The first time the Rate Limit is hit, it is handled correctly. 

In the retry, 
But in the retry, stravalib seems to not raise a stravalib.exc.RateLimitExceeded, but a generic stravalib.exc.Fault with Error Code 429; which is not handled

```
2024-06-24 07:47:53 geo_activity_playground.core.cache_migrations INFO Apply cache migration if needed …
Downloading Strava activities: 134it [00:56,  1.04s/it]
2024-06-24 07:48:59 stravalib.util.limiter.SleepingRateLimitRule WARNING Short term API rate limit exceeded
2024-06-24 07:59:59 stravalib.util.limiter.SleepingRateLimitRule WARNING Short term API rate limit exceeded
Downloading Strava activities: 134it [11:56,  5.35s/it]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/geo_activity_playground/__main__.py", line 118, in <module>
    main()
  File "/app/geo_activity_playground/__main__.py", line 93, in main
    options.func(options)
  File "/app/geo_activity_playground/__main__.py", line 67, in <lambda>
    *make_activity_repository(options.basedir, options.skip_strava),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/geo_activity_playground/__main__.py", line 112, in make_activity_repository
    scan_for_activities(repository, tile_visit_accessor, config, skip_strava)
  File "/app/geo_activity_playground/webui/upload/controller.py", line 104, in scan_for_activities
    import_from_strava_api(repository)
  File "/app/geo_activity_playground/importers/strava_api.py", line 96, in import_from_strava_api
    while try_import_strava(repository):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/geo_activity_playground/importers/strava_api.py", line 157, in try_import_strava
    detailed_activity = get_detailed_activity(activity.id, client)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/geo_activity_playground/importers/strava_api.py", line 208, in get_detailed_activity
    detailed_activity = client.get_activity(activity_id)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/stravalib/client.py", line 614, in get_activity
    raw = self.protocol.get(
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/stravalib/protocol.py", line 440, in get
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/stravalib/protocol.py", line 325, in _request
    self._handle_protocol_error(raw)
  File "/usr/local/lib/python3.11/site-packages/stravalib/protocol.py", line 376, in _handle_protocol_error
    raise exc.Fault(msg, response=response)
stravalib.exc.Fault: 429 Client Error: Too Many Requests [Rate Limit Exceeded: [{'resource': 'Application', 'field': 'read rate limit', 'code': 'exceeded'}]]
```

**Comment by martin-ueding** [comment]
I have tried to catch this:

```python
    except Fault as e:
        if "Too Many Requests" in str(e):
            limit_exceeded = True
        else:
            raise
```

This will be part of 0.24.0. Can you check whether that works for you?

**Comment by p3dda** [comment]
I have just tested your fix and can confirm that it works correctly.
