### ISSUE TITLE
Probleme beim Serverstart

### ISSUE THREAD

**Issue by Hanfbaum** [martin-ueding/geo-activity-playground#124]
Hallo Martin
Programm startet und nach dem Download von ein paar Dateien stürztes ab und startet keinen Server für die Website.

```
2024-07-26 19:55:13 geo_activity_playground.core.cache_migrations INFO Applying cache migration delete_everything …
Downloading Strava activities: 10it [00:13,  1.17it/s]2024-07-26 19:55:30 geo_activity_playground.importers.strava_api ERROR The activity 707566273 with name “Radfahrt nachts” cannot be found.Perhaps it is a manual activity without a time series. Ignoring. e=ObjectNotFound('Not Found: Resource Not Found: []')
Downloading Strava activities: 49it [00:47,  1.03it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 118, in <module>
    main()
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 93, in main
    options.func(options)
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 67, in <lambda>
    *make_activity_repository(options.basedir, options.skip_strava),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 112, in make_activity_repository
    scan_for_activities(repository, tile_visit_accessor, config, skip_strava)
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\webui\upload\controller.py", line 105, in scan_for_activities
    import_from_strava_api(repository)
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\importers\strava_api.py", line 97, in import_from_strava_api
    while try_import_strava(repository):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\importers\strava_api.py", line 183, in try_import_strava
    repository.commit()
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\core\activities.py", line 92, in commit
    assert pd.api.types.is_dtype_equal(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: (datetime64[ns, UTC], Timestamp('2016-08-28 18:16:18+0000', tz='UTC'))
E:\Martin\Playground_Strava>pause
```

**Comment by martin-ueding** [comment]
Kannst du nochmal mit Version 0.24 versuchen, die ich eben veröffentlicht habe? Damit konnte dieses Zeitzonen-Problem weg sein.

**Comment by Hanfbaum** [comment]
Es ist schon die neue Version 0.24.

**Comment by Hanfbaum** [comment]
Es scheint mit 0.24.1 behoben zu sein. Rate limit und automatischer restart funktioniert. Hab im moment nur den Zugang über Strava API. Download dauert also noch ein bisschen.
