### ISSUE TITLE
Heatmap download broken

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/geo-activity-playground#126]
```
Traceback (most recent call last):
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/webui/heatmap/blueprint.py", line 34, in download
    heatmap_controller.download_heatmap(
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/webui/heatmap/heatmap_controller.py", line 144, in download_heatmap
    background = np.zeros((*tile_bounds.shape, 3))
AttributeError: 'TileBounds' object has no attribute 'shape'
```

**Comment by martin-ueding** [comment]
Fixed in 0.24.1.
