### ISSUE TITLE
Server startet nicht

### ISSUE THREAD

**Issue by Hanfbaum** [martin-ueding/geo-activity-playground#129]
Es müssten alle Aktivitäten runtergeladen worden sein. Der Server startet aber nicht, sondern wirft den folgenden Fehler.
Version 0.24.2
```
2024-07-31 10:48:44 geo_activity_playground.core.cache_migrations INFO Apply cache migration if needed …
Downloading Strava activities: 0it [00:00, ?it/s]
Embellish time series data:   0%|                                                             | 0/2132 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 118, in <module>
    main()
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 93, in main
    options.func(options)
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 67, in <lambda>
    *make_activity_repository(options.basedir, options.skip_strava),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 112, in make_activity_repository
    scan_for_activities(repository, tile_visit_accessor, config, skip_strava)
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\webui\upload\controller.py", line 113, in scan_for_activities
    embellish_time_series(repository)
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\core\activities.py", line 164, in embellish_time_series
    df, changed = embellish_single_time_series(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\core\activities.py", line 187, in embellish_single_time_series
    assert pd.api.types.is_dtype_equal(timeseries["time"].dtype, "datetime64[ns]")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

E:\Martin\Playground_Strava>pause
Drücken Sie eine beliebige Taste . . .
```

**Comment by Oi-sin** [comment]
Ich habe die letzten 2,5 Tage auch den Strava-API-Download mit komplett geleertem Cache durchlaufen lassen. Ich bekomme ebenfalls diesen Fehler mit diesem callstack.

**Comment by martin-ueding** [comment]
Ich konnte es jetzt auch reproduzieren und verstehen, warum das so passiert. Ist jetzt repariert und sollte in der nächsten Version dann behoben sein.
