### ISSUE TITLE
Summary page generation fails if no activity has steps

### ISSUE THREAD

**Issue by antonmosich** [martin-ueding/geo-activity-playground#141]
```
2024-08-06 14:42:13 py.warnings WARNING /nix/store/cxzm76qf84jd1kymjwp2b3si4z95rmm9-geo-activity-playground-0.26.1/lib/python3.12/site-packages/geo_activity_playground/webui/summary/controller.py:69: FutureWarning: The behavior of Series.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  i = subset["steps"].idxmax()

2024-08-06 14:42:13 geo_activity_playground.webui.app ERROR Exception on /summary/ [GET]
Traceback (most recent call last):
  File "/nix/store/h95lbryj8h6p0iq3jymbn0zgvswpibf7-python3.12-pandas-2.2.2/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 175, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index_class_helper.pxi", line 70, in pandas._libs.index.Int64Engine._check_type
KeyError: nan

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/wmkpfdla775w4rhbririk7hll46hd3y1-python3.12-flask-3.0.3/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wmkpfdla775w4rhbririk7hll46hd3y1-python3.12-flask-3.0.3/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wmkpfdla775w4rhbririk7hll46hd3y1-python3.12-flask-3.0.3/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wmkpfdla775w4rhbririk7hll46hd3y1-python3.12-flask-3.0.3/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/cxzm76qf84jd1kymjwp2b3si4z95rmm9-geo-activity-playground-0.26.1/lib/python3.12/site-packages/geo_activity_playground/webui/summary/blueprint.py", line 14, in index
    return render_template("summary/index.html.j2", **summary_controller.render())
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/cxzm76qf84jd1kymjwp2b3si4z95rmm9-geo-activity-playground-0.26.1/lib/python3.12/site-packages/geo_activity_playground/webui/summary/controller.py", line 46, in render
    for activity_id, reasons in nominate_activities(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/cxzm76qf84jd1kymjwp2b3si4z95rmm9-geo-activity-playground-0.26.1/lib/python3.12/site-packages/geo_activity_playground/webui/summary/controller.py", line 70, in nominate_activities
    nominations[i].append(f"Most steps: {meta.loc[i].steps:.0f}")
                                         ~~~~~~~~^^^
  File "/nix/store/h95lbryj8h6p0iq3jymbn0zgvswpibf7-python3.12-pandas-2.2.2/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/h95lbryj8h6p0iq3jymbn0zgvswpibf7-python3.12-pandas-2.2.2/lib/python3.12/site-packages/pandas/core/indexing.py", line 1431, in _getitem_axis
    return self._get_label(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/h95lbryj8h6p0iq3jymbn0zgvswpibf7-python3.12-pandas-2.2.2/lib/python3.12/site-packages/pandas/core/indexing.py", line 1381, in _get_label
    return self.obj.xs(label, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/h95lbryj8h6p0iq3jymbn0zgvswpibf7-python3.12-pandas-2.2.2/lib/python3.12/site-packages/pandas/core/generic.py", line 4301, in xs
    loc = index.get_loc(key)
          ^^^^^^^^^^^^^^^^^^
  File "/nix/store/h95lbryj8h6p0iq3jymbn0zgvswpibf7-python3.12-pandas-2.2.2/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: nan
```

**Comment by martin-ueding** [comment]
Thanks for the report! I managed to get a test case that catches this. Will be fixed in 0.26.2 that I'll release soon.
