### ISSUE TITLE
Error from pandas time function

### ISSUE THREAD

**Issue by ragnar76** [martin-ueding/geo-activity-playground#150]
After updating my setup, i get this error:
```
File "timestamps.pyx", line 387, in pandas._libs.tslibs.timestamps._Timestamp.__richcmp__
TypeError: Cannot compare tz-naive and tz-aware timestamps
```

**Comment by ragnar76** [comment]
Here's the complete message:

```
root@rpi5:~/src/geo-activity-playground # docker run -p 5000:5000 -v /var/www/tracks/gpx-tracks:/data -it geo-activity-playground
Detect deleted activities: 0it [00:00, ?it/s]
Parse activity metadata (concurrently): 0it [00:00, ?it/s]
Collate activity metadata: 0it [00:00, ?it/s]
Enrich new activity data: 0it [00:00, ?it/s]
Register new activities: 0it [00:00, ?it/s]
Extract explorer tile visits: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 18.90it/s]
Incorporate changes in tiles:   0%|                                                                                                                                         | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/geo_activity_playground/__main__.py", line 120, in <module>
    main()
  File "/app/geo_activity_playground/__main__.py", line 93, in main
    options.func(options)
  File "/app/geo_activity_playground/__main__.py", line 67, in <lambda>
    *make_activity_repository(options.basedir, options.skip_strava),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/geo_activity_playground/__main__.py", line 112, in make_activity_repository
    scan_for_activities(
  File "/app/geo_activity_playground/webui/upload/controller.py", line 118, in scan_for_activities
    compute_tile_visits(repository, tile_visit_accessor)
  File "/app/geo_activity_playground/explorer/tile_visits.py", line 151, in compute_tile_visits
    df.sort_values("time", inplace=True)
  File "/usr/local/lib/python3.11/site-packages/pandas/core/frame.py", line 7200, in sort_values
    indexer = nargsort(
              ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/core/sorting.py", line 439, in nargsort
    indexer = non_nan_idx[non_nans.argsort(kind=kind)]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "timestamps.pyx", line 387, in pandas._libs.tslibs.timestamps._Timestamp.__richcmp__
TypeError: Cannot compare tz-naive and tz-aware timestamps
```

**Comment by martin-ueding** [comment]
In the `Cache`, could you delete `activities-per-tile.pickle`, `tile-evolution-state.pickle`, `tile-history.pickle`, `tile-visits.pickle` and `work-tracker-tile-visits.pickle` and then try again?

**Comment by ragnar76** [comment]
haven't had a file called activities-per-tile.pickle but deleted the other ones. It works again

**Comment by ragnar76** [comment]
No i get this:
```

2024-08-10 17:30:27 geo_activity_playground.webui.app ERROR Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/geo_activity_playground/webui/app.py", line 46, in index
    return render_template("home.html.j2", **entry_controller.render())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 127, in _render
    app.update_template_context(context)
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 493, in update_template_context
    context.update(self.ensure_sync(func)())
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/geo_activity_playground/webui/app.py", line 125, in inject_global_variables
    "version": importlib.metadata.version("geo-activity-playground"),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 1009, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 982, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for geo-activity-playground
```
