### ISSUE TITLE
Heatmap seems to access deleted activities

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/geo-activity-playground#163]
The heatmap gets confused when there are deleted activities:

```
2024-09-16 13:13:53 geo_activity_playground.webui.app ERROR Exception on /heatmap/tile/14/8515/5504/Autofahrt;Bahnfahrt;Busfahrt;Lauf;Radfahrt;Spaziergang;Wanderung.png [GET]
Traceback (most recent call last):
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib64/python3.9/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2606, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2630, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 2476720129193883726

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/webui/heatmap/blueprint.py", line 27, in tile
    heatmap_controller.render_tile(int(x), int(y), int(z), kinds.split(";")),
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/webui/heatmap/heatmap_controller.py", line 155, in render_tile
    pl.imsave(f, self._render_tile_image(x, y, z, kinds), format="png")
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/webui/heatmap/heatmap_controller.py", line 135, in _render_tile_image
    tile_counts += self._get_counts(x, y, z, kind)
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/webui/heatmap/heatmap_controller.py", line 107, in _get_counts
    activity = self._repository.get_activity_by_id(activity_id)
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/core/activities.py", line 145, in get_activity_by_id
    activity = self.meta.loc[id]
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib64/python3.9/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib64/python3.9/site-packages/pandas/core/indexing.py", line 1431, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib64/python3.9/site-packages/pandas/core/indexing.py", line 1381, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib64/python3.9/site-packages/pandas/core/generic.py", line 4301, in xs
    loc = index.get_loc(key)
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.9/lib64/python3.9/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 2476720129193883726
```

**Comment by martin-ueding** [comment]
I recompute the whole tile state when there are deleted activities. Now that the recomputation is done in a few minutes, that's acceptable. Also it will be completely consistent at all times, which is a plus.
