### ISSUE TITLE
Andere Dateien als GPS/FIT crashen den scan

### ISSUE THREAD

**Issue by multiburst** [martin-ueding/geo-activity-playground#169]
Da ich lange schon Routen aufzeichne, würde ich gern mein bestehendes Verzeichnis mit allen Tracks benutzen.

Allerdings habe ich immer so wohl GPX als auch KML Aufzeichnungen exportiert.

Leider crasht das Scannen der Activities, wenn Dateien die nicht GPX/FIT sind vorliegen. Also bei KML/KMZ, aber vermute mal bei fast allen artfremden Dateien.

```
2024-09-30 19:06:50 geo_activity_playground.importers.directory ERROR Encountered a problem with path=PosixPath('Activities/alle chronologisch/2022/2022-06-19 124559__20220619_1245.kml'), see details below.
Parse activity metadata (serially):   0%|                                                                   | 2/2090 [00:00<00:58, 35.95it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/data/coding/GPS/geo-activity-playground/geo_activity_playground/__main__.py", line 91, in main
    options.func(options)
  File "/mnt/data/coding/GPS/geo-activity-playground/geo_activity_playground/__main__.py", line 67, in <lambda>
    *make_activity_repository(options.basedir, options.skip_reload),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/coding/GPS/geo-activity-playground/geo_activity_playground/__main__.py", line 106, in make_activity_repository
    scan_for_activities(repository, tile_visit_accessor, config_accessor())
  File "/mnt/data/coding/GPS/geo-activity-playground/geo_activity_playground/webui/upload/controller.py", line 104, in scan_for_activities
    import_from_directory(
  File "/mnt/data/coding/GPS/geo-activity-playground/geo_activity_playground/importers/directory.py", line 65, in import_from_directory
    errors = _cache_single_file(path)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/coding/GPS/geo-activity-playground/geo_activity_playground/importers/directory.py", line 119, in _cache_single_file
    activity_meta_from_file, timeseries = read_activity(path)
                                          ^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/coding/GPS/geo-activity-playground/geo_activity_playground/importers/activity_parsers.py", line 57, in read_activity
    timeseries = read_kml_activity(path, opener)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/coding/GPS/geo-activity-playground/geo_activity_playground/importers/activity_parsers.py", line 250, in read_kml_activity
    placemark = keypoint_folder["Placemark"]
                ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

**Comment by martin-ueding** [comment]
Die Struktur dieser KML-Datei wird nicht richtig verarbeitet. Könntest du mir vielleicht die Datei schicken, damit ich das ausbessern kann? ***@***.***)

Am 30. September 2024 19:14:10 MESZ schrieb multiburst ***@***.***>:

**Comment by multiburst** [comment]
Aber gern. Hab sie hier angehangen, enthält nichts persönliches.

Wenn es an der Struktur liegt: hätte ich gern auch ein Feature (sag gern, wenn ich das nochmal getrennt aufmachen soll).

Da die Tracks doppelt als GPX/KML vorliegen, wäre eine Filterung für den Scan sinnvoll. Gern auch einfach nur als config/text Filter. Gibt glaub einige Tools, die nach Routenende mehrere Formate ausspucken - und das irritiert ja dann jegliche Statistik.

Textdatei oder Parameter mit den Formaten zum ein/ausschließen wäre dann der Wunsch. Oder einfach KML/Z ignorieren ;)

[2022-06-19 124559__20220619_1245.kml.zip](https://github.com/user-attachments/files/17194995/2022-06-19.124559__20220619_1245.kml.zip)

**Comment by martin-ueding** [comment]
![image](https://github.com/user-attachments/assets/22afd0ab-e71e-4024-9063-416d179dc5e6)

Da waren wohl noch Wegpunkte drin. Kann aber jetzt importiert werden.

**Comment by martin-ueding** [comment]
Für das andere habe ich ein neues Ticket eröffnet: https://github.com/martin-ueding/geo-activity-playground/issues/173

**Comment by multiburst** [comment]
Hab direkt noch eine nicht funktionierende Datei gefunden.

(wobei mir persönlich der Filter für bestimmte Dateiformate wichtiger wäre ;))

`ValueError: day is out of range for month`

[2022-06-20 122513__20220620_1225.kml.zip](https://github.com/user-attachments/files/17247753/2022-06-20.122513__20220620_1225.kml.zip)
