### ISSUE TITLE
Problem with activities.csv from Strava

### ISSUE THREAD

**Issue by ritterjo** [martin-ueding/geo-activity-playground#191]
I downloaded my Strava data and started geo-activity-playground (Version 0.31.0) but it fails with the following message:

```
geo_activity_playground.importers.directory ERROR Encountered a problem with path=WindowsPath('Activities/Strava Export/activities.csv'), see details below.
```

After looking into the csv file I saw that the column names are in German. Maybe thats the problem?

It was not clear to me if I need to run the `convert-strava-checkout` or if the extracted zip from Strava is enough?

Here is the header line of the `activities.csv`:

```
Aktivitäts-ID,Aktivitätsdatum,Name der Aktivität,Aktivitätsart,Aktivitätsbeschreibung,Verstrichene Zeit,Distanz,Max. Herzfrequenz,Relative Leistung,Pendeln,Hinweis zur Privatsphäre für Aktivitäten,Aktivitätsausrüstung,Dateiname,Sportlergewicht,Fahrradgewicht,Verstrichene Zeit,Bewegungszeit,Distanz,Höchstgeschw.,Durchschnittliche Geschwindigkeit,Höhenzunahme,Höhenunterschied,Min. Höhe,Max. Höhe,Max. Steigung,Durchschnittliche Steigung,Durchschnittliche positive Steigung,Durchschnittliche negative Steigung,Max. Tritt-/Schrittfrequenz,Durchschnittliche Trittfrequenz,Max. Herzfrequenz,Durchschnittliche Herzfrequenz,Max. Watt,Durchschnittliche Watt,Kalorien,Max. Temperatur,Durchschnittliche Temperatur,Relative Leistung,Gesamtarbeit,Anzahl Läufe,Bergaufzeit,Bergabzeit,Andere Zeit,Gefühlte Anstrengung,Art,Startzeit,Gewichtete durchschnittliche Leistung,Leistungszahl,Gefühlte Anstrengung verwenden,Gefühlte relative Leistung,Pendeln,Insgesamt gestemmtes Gewicht,Von Upload,Auf Steigung angepasste Distanz,Wetterbeobachtungszeit,Wetterlage,Wetter: Temperatur,Scheinbare Temperatur,Taupunkt,Luftfeuchtigkeit,Wetter: Druck,Windgeschwindigkeit,Windböe,Windrichtung,Niederschlagsintensität,Sonnenaufgangszeit,Sonnenuntergangszeit,Mondphase,Fahrrad,Ausrüstung,Niederschlagswahrscheinlichkeit,Niederschlagsart,Wolkendecke,Wetter: Sichtbarkeit,UV-Index,Wetter: Ozon,Sprunganzahl,Schwierigkeit insgesamt,Durchschnittlicher Flow,Markiert,Durchschnittsgeschwindigkeit im Aufzeichnungszeitraum,Auf Schotter zurückgelegte Distanz,Neu getestete Distanz,Neu getestete Schotterdistanz,Aktivitätsanzahl,Schritte insgesamt,Eingesparte CO₂-Emissionen,Pool-Länge,Trainingsbelastung,Intensität,Durchschnittliches auf Steigung angepasstes Tempo,Stoppuhr-Zeit,Zyklen gesamt,Medien
```

Full stacktrace:

```
C:\Users\Jonas\Documents\Playground-Directory>python -m geo_activity_playground serve
Detect deleted activities: 100%|██████████████████████████████████████████████████| 1228/1228 [00:11<00:00, 104.60it/s]
Parse activity metadata (serially):   0%|                                                     | 0/1228 [00:00<?, ?it/s]2024-11-05 22:19:21 geo_activity_playground.importers.directory ERROR Encountered a problem with path=WindowsPath('Activities/Strava Export/activities.csv'), see details below.
Parse activity metadata (serially):   0%|                                                     | 0/1228 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'timeStamp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\geo_activity_playground\__main__.py", line 118, in <module>
    main()
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\geo_activity_playground\__main__.py", line 91, in main
    options.func(options)
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\geo_activity_playground\__main__.py", line 67, in <lambda>
    *make_activity_repository(options.basedir, options.skip_reload),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\geo_activity_playground\__main__.py", line 106, in make_activity_repository
    scan_for_activities(repository, tile_visit_accessor, config_accessor())
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\geo_activity_playground\webui\upload\controller.py", line 104, in scan_for_activities
    import_from_directory(
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\geo_activity_playground\importers\directory.py", line 65, in import_from_directory
    errors = _cache_single_file(path)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\geo_activity_playground\importers\directory.py", line 119, in _cache_single_file
    activity_meta_from_file, timeseries = read_activity(path)
                                          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\geo_activity_playground\importers\activity_parsers.py", line 59, in read_activity
    timeseries = read_simra_activity(path, opener)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\geo_activity_playground\importers\activity_parsers.py", line 282, in read_simra_activity
    data["time"] = data["timeStamp"].apply(
                   ~~~~^^^^^^^^^^^^^
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'timeStamp'

C:\Users\Jonas\Documents\Playground-Directory>pause
Drücken Sie eine beliebige Taste . . . 
````

**Comment by martin-ueding** [comment]
Hi there! This is a really subtle thing gone wrong: You have the `Strava Export` inside the `Activities`. But the `Strava Export` needs to be on the top level, so `Playground/Strava Export`. Just move that directory up one level and try again.

Inside `Activities` all the files are expected to be some sort of activity files. So it found `Activities/Strava Export/activities.csv` and assumed these were Simra files and tried to import them as such.

Feel free to reopen if that doesn't help.
