### ISSUE TITLE
Import Probleme

### ISSUE THREAD

**Issue by Hanfbaum** [martin-ueding/geo-activity-playground#197]
Scheint Probleme beim Import zugeben. Server startet durch das Problem nicht

```
E:\Martin\Playground_Strava>python -m geo_activity_playground serve
2024-11-14 23:13:32 geo_activity_playground.core.config WARNING You have an old 'config.toml' which is now superseded by the 'config.json'. You can check the contents of the new 'config.json' and then delete the old 'config.toml'.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 118, in <module>
    main()
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 91, in main
    options.func(options)
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 67, in <lambda>
    *make_activity_repository(options.basedir, options.skip_reload),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 106, in make_activity_repository
    scan_for_activities(repository, tile_visit_accessor, config_accessor())
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\webui\upload\controller.py", line 108, in scan_for_activities
    import_from_strava_checkout()
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\importers\strava_checkout.py", line 150, in import_from_strava_checkout
    rows = parse_csv(f.read())
                     ^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 933063: character maps to <undefined>

E:\Martin\Playground_Strava>pause
Drücken Sie eine beliebige Taste . . .
```

**Comment by martin-ueding** [comment]
Das Problem ist das Character-Encoding deiner CSV-Datei. Kannst du mal mit einem Programmierer-Texteditor schauen, ob das UTF-8 ist? Oder mir die Datei `activities.csv` einmal schicken?

**Comment by Hanfbaum** [comment]
Wenn ich das Programm richtig verstehe müsste es UTF-8 sein. Habe dir die Datei mal als Mail geschickt.

**Comment by waeller** [comment]
Ich hatte den Fehler auch (allerdings mit "...byte 0x8f..."). Nachdem ich alle Emojis aus Titeln und Beschreibungen in der activities.csv  entfernt hatte, lief es weiter. Jetzt bekomme ich diesen Fehler:

```
C:\Users\scum36\Documents\GeoActivityPlayground>python -m geo_activity_playground serve
Detect deleted activities: 0it [00:00, ?it/s]
Parse activity metadata (serially): 0it [00:00, ?it/s]
Collate activity metadata: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\scum36\AppData\Roaming\Python\Python312\site-packages\geo_activity_playground\__main__.py", line 118, in <module>
    main()
  File "C:\Users\scum36\AppData\Roaming\Python\Python312\site-packages\geo_activity_playground\__main__.py", line 91, in main
    options.func(options)
  File "C:\Users\scum36\AppData\Roaming\Python\Python312\site-packages\geo_activity_playground\__main__.py", line 67, in <lambda>
    *make_activity_repository(options.basedir, options.skip_reload),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\scum36\AppData\Roaming\Python\Python312\site-packages\geo_activity_playground\__main__.py", line 106, in make_activity_repository
    scan_for_activities(repository, tile_visit_accessor, config_accessor())
  File "C:\Users\scum36\AppData\Roaming\Python\Python312\site-packages\geo_activity_playground\webui\upload\controller.py", line 108, in scan_for_activities
    import_from_strava_checkout()
  File "C:\Users\scum36\AppData\Roaming\Python\Python312\site-packages\geo_activity_playground\importers\strava_checkout.py", line 169, in import_from_strava_checkout
    all_activity_ids = [int(value) for value in table["Activity ID"]]
                                                ~~~~~^^^^^^^^^^^^^^^
KeyError: 'Activity ID'

```

**Comment by martin-ueding** [comment]
Kann es sein, dass ihr beide Windows nutzt?

In der Dokumentation zu `open` steht das hier:

> `encoding` is the name of the encoding used to decode or encode the file. This should only be used in text mode. The default encoding is platform dependent, but any encoding supported by Python can be passed. See the codecs module for the list of supported encodings.

In Hanfbaums Fehlermeldung steht "'charmap' codec". Ich glaube, dass Windows hier mal wieder etwas anderes als UTF-8 macht. Ich setze das mal als Standard.

**Comment by martin-ueding** [comment]
@waeller: Kannst du mir einmal die erste Zeile deiner CSV-Datei hier reinkopieren? Ich erwarte entweder "Activity ID" oder "Aktivitäts-ID". Strava hat es dann wohl schon wieder verändert …

**Comment by martin-ueding** [comment]
Sollte dann in 0.34.0 behoben sein.

**Comment by waeller** [comment]
> @waeller: Kannst du mir einmal die erste Zeile deiner CSV-Datei hier reinkopieren? Ich erwarte entweder "Activity ID" oder "Aktivitäts-ID". Strava hat es dann wohl schon wieder verändert …

Die erste Zeile sieht so aus:

Aktivitäts-ID,Aktivitätsdatum,Name der Aktivität,Aktivitätsart,Aktivitätsbeschreibung,Verstrichene Zeit,Distanz,Max. Herzfrequenz,Relative Leistung,Pendeln,Hinweis zur Privatsphäre für Aktivitäten,Aktivitätsausrüstung,Dateiname,Sportlergewicht,Fahrradgewicht,Verstrichene Zeit,Bewegungszeit,Distanz,Höchstgeschw.,Durchschnittliche Geschwindigkeit,Höhenzunahme,Höhenunterschied,Min. Höhe,Max. Höhe,Max. Steigung,Durchschnittliche Steigung,Durchschnittliche positive Steigung,Durchschnittliche negative Steigung,Max. Tritt-/Schrittfrequenz,Durchschnittliche Trittfrequenz,Max. Herzfrequenz,Durchschnittliche Herzfrequenz,Max. Watt,Durchschnittliche Watt,Kalorien,Max. Temperatur,Durchschnittliche Temperatur,Relative Leistung,Gesamtarbeit,Anzahl Läufe,Bergaufzeit,Bergabzeit,Andere Zeit,Gefühlte Anstrengung,Art,Startzeit,Gewichtete durchschnittliche Leistung,Leistungszahl,Gefühlte Anstrengung verwenden,Gefühlte relative Leistung,Pendeln,Insgesamt gestemmtes Gewicht,Von Upload,Auf Steigung angepasste Distanz,Wetterbeobachtungszeit,Wetterlage,Wetter: Temperatur,Scheinbare Temperatur,Taupunkt,Luftfeuchtigkeit,Wetter: Druck,Windgeschwindigkeit,Windböe,Windrichtung,Niederschlagsintensität,Sonnenaufgangszeit,Sonnenuntergangszeit,Mondphase,Fahrrad,Ausrüstung,Niederschlagswahrscheinlichkeit,Niederschlagsart,Wolkendecke,Wetter: Sichtbarkeit,UV-Index,Wetter: Ozon,Sprunganzahl,Schwierigkeit insgesamt,Durchschnittlicher Flow,Markiert,Durchschnittsgeschwindigkeit im Aufzeichnungszeitraum,Auf Schotter zurückgelegte Distanz,Neu getestete Distanz,Neu getestete Schotterdistanz,Aktivitätsanzahl,Schritte insgesamt,Eingesparte CO₂-Emissionen,Pool-Länge,Trainingsbelastung,Intensität,Durchschnittliches auf Steigung angepasstes Tempo,Stoppuhr-Zeit,Zyklen gesamt,Medien

Vielleicht liegt's ja an dem gleichen UTF-8-Problem, so dass das "ä" nicht richtig ankommt. Ich probier das nach dem Update nochmal. Oder unter Linux.

**Comment by waeller** [comment]
Ja, mit der 0.34.0 läuft der Import durch. Vielen Dank (:

**Comment by martin-ueding** [comment]
Wunderbar! Dann war es wirklich schlicht das Problem, dass Python in Windows nicht UTF-8 als Standard nimmt. Das erklärt auch, warum ich das unter Linux nicht reproduzieren konnte.
