### ISSUE TITLE
Filter NaN in speed

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/geo-activity-playground#21]
```
2023-11-25 21:43:52 geo_activity_playground.webui.app ERROR Exception on /activity/7005273466 [GET]
Traceback (most recent call last):
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.11/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.11/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.11/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.11/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/webui/app.py", line 38, in activity
    "activity.html.j2", **activity_controller.render_activity(int(id))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/webui/activity_controller.py", line 29, in render_activity
    "color_line_geojson": make_geojson_color_line(time_series),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mu/Projekte/geo-activity-playground/geo_activity_playground/core/activities.py", line 80, in make_geojson_color_line
    return geojson.dumps(
           ^^^^^^^^^^^^^^
  File "/home/mu/.cache/pypoetry/virtualenvs/geo-activity-playground-cM-Vn1fX-py3.11/lib/python3.11/site-packages/geojson/codec.py", line 31, in dumps
    return json.dumps(to_mapping(obj),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
ValueError: Out of range float values are not JSON compliant
```

**Comment by martin-ueding** [comment]
Added a small epsilon.
