### ISSUE TITLE
ERROR when opening "Explorer" register

### ISSUE THREAD

**Issue by sbrenner1982** [martin-ueding/geo-activity-playground#51]
Release 0.11
Python 3.11
Windows 10 Firefox 120.0.1

When I switch to the "Explorer" register, the browser shows:
---
"Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
---

console log:
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Building explorer tile history from all activities …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 3910550516679418123 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 3910550516679418123 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 665755070860271319 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 665755070860271319 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 3116701884354287046 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 3116701884354287046 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 2815321982939008029 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 2815321982939008029 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 2057157721423401396 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 2057157721423401396 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 1024879950318135356 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 1024879950318135356 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 4097627365468579779 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 4097627365468579779 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 722687832335573953 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 722687832335573953 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 1915198705200252476 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 1915198705200252476 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 131465637476262493 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 131465637476262493 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 845606888006357819 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 845606888006357819 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 3464218740280590283 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 3464218740280590283 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 2444638013619293738 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 2444638013619293738 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 2509769455157063981 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 2509769455157063981 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Activity 1818155451184888134 wasn't parsed yet, reading them …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Extracting tiles from activity 1818155451184888134 …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Consolidating explorer tile history …
2023-12-06 22:44:59 geo_activity_playground.explorer.converters INFO Store explorer tile history to cache file …
2023-12-06 22:44:59 geo_activity_playground.explorer.clusters INFO Loading explorer cluster state …
2023-12-06 22:44:59 geo_activity_playground.explorer.clusters INFO Compute new explorer cluster state …
2023-12-06 22:44:59 geo_activity_playground.explorer.clusters INFO Saving explorer cluster state …
2023-12-06 22:44:59 geo_activity_playground.explorer.grid_file INFO Generate data for explorer tile map …
2023-12-06 22:44:59 geo_activity_playground.explorer.clusters INFO Load explorer square state …
2023-12-06 22:44:59 geo_activity_playground.explorer.clusters INFO Compute new explorer square state …
2023-12-06 22:44:59 geo_activity_playground.explorer.clusters INFO Save explorer square state …
2023-12-06 22:44:59 geo_activity_playground.explorer.grid_file INFO Generate border tiles …
2023-12-06 22:44:59 geo_activity_playground.webui.app ERROR Exception on /explorer/14 [GET]
Traceback (most recent call last):
  File "C:\envs\311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\geo_activity_playground\webui\app.py", line 60, in explorer
    "explorer.html.j2", **explorer_controller.render(int(zoom))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\geo_activity_playground\webui\explorer_controller.py", line 62, in render
    "plot_cluster_evolution": plot_cluster_evolution(
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\geo_activity_playground\webui\explorer_controller.py", line 94, in plot_cluster_evolution
    .to_json(format="vega")
     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\altair\vegalite\v5\api.py", line 1042, in to_json
    spec = self.to_dict(
           ^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\altair\vegalite\v5\api.py", line 2975, in to_dict
    return super().to_dict(
           ^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\altair\vegalite\v5\api.py", line 961, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\altair\utils\schemapi.py", line 961, in to_dict
    result = _todict(
             ^^^^^^^^
  File "C:\envs\311\Lib\site-packages\altair\utils\schemapi.py", line 477, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\altair\utils\schemapi.py", line 477, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
               ^^^^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\altair\utils\schemapi.py", line 473, in _todict
    return obj.to_dict(validate=False, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\altair\utils\schemapi.py", line 961, in to_dict
    result = _todict(
             ^^^^^^^^
  File "C:\envs\311\Lib\site-packages\altair\utils\schemapi.py", line 477, in _todict
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\altair\utils\schemapi.py", line 477, in <dictcomp>
    return {k: _todict(v, context) for k, v in obj.items() if v is not Undefined}
               ^^^^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\altair\utils\schemapi.py", line 473, in _todict
    return obj.to_dict(validate=False, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\envs\311\Lib\site-packages\altair\vegalite\v5\schema\channels.py", line 64, in to_dict
    raise ValueError(
ValueError: Unable to determine data type for the field "time"; verify that the field name is not misspelled. If you are referencing a field from a transform, also confirm that the data type is specified correctly.
2023-12-06 22:44:59 werkzeug INFO 127.0.0.1 - - [06/Dec/2023 22:44:59] "GET /explorer/14 HTTP/1.1" 500 -
2023-12-06 22:45:00 werkzeug INFO 127.0.0.1 - - [06/Dec/2023 22:45:00] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by martin-ueding** [comment]
I've fixed that in 0.12.0, which I just released.
