### ISSUE TITLE
Value error 

### ISSUE THREAD

**Issue by Natenom** [martin-ueding/geo-activity-playground#56]
Current master. Removed the `Cache` directory, added a `Cache/status.json` manually and started. When opening Explorer 14/17, this happens:

```
2023-12-10 09:54:34 geo_activity_playground.explorer.converters INFO Building explorer tile history from all activities …
2023-12-10 09:54:34 geo_activity_playground.explorer.converters INFO Activity 2870823093039122292 wasn't parsed yet, reading them …
2023-12-10 09:54:34 geo_activity_playground.webui.app ERROR Exception on /explorer/17 [GET]
Traceback (most recent call last):
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my/src/github/geo-activity-playground/geo_activity_playground/webui/app.py", line 60, in explorer
    "explorer.html.j2", **explorer_controller.render(int(zoom))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my/src/github/geo-activity-playground/geo_activity_playground/webui/explorer_controller.py", line 30, in render
    tiles = get_tile_history(self._repository, zoom)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my/src/github/geo-activity-playground/geo_activity_playground/explorer/converters.py", line 103, in get_tile_history
    shard = get_first_tiles(activity.id, repository, zoom)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my/src/github/geo-activity-playground/geo_activity_playground/explorer/converters.py", line 29, in get_first_tiles
    tiles = tiles_from_points(time_series, zoom)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my/src/github/geo-activity-playground/geo_activity_playground/explorer/converters.py", line 42, in tiles_from_points
    for t1, t2, x1, y1, x2, y2, s1, s2 in zip(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 8, got 7)
```

**Comment by martin-ueding** [comment]
Oh, I did a stupid mistake and didn't test it. I've fixed it now and verified that it works.

Thank you for testing all the `master` versions! 😊
