### ISSUE TITLE
Missing dependency for scikit-learn

### ISSUE THREAD

**Issue by p3dda** [martin-ueding/geo-activity-playground#59]
There seems to be a dependency missing in pyproject.tomp.

After installation from git on a clean linux environment (python 3.11), I get following traceback:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/src/geo_activity_playground/__main__.py", line 11, in <module>
    from geo_activity_playground.heatmap import generate_heatmaps_per_cluster
  File "/src/geo_activity_playground/heatmap.py", line 7, in <module>
    import sklearn.cluster
ModuleNotFoundError: No module named 'sklearn'
``` 

Neither scikit-learn nor sklearn (which is deprecated anyways) is listed in the pyproject.toml

**Comment by martin-ueding** [comment]
Thanks for the report! I was too eager to remove it after changing the way that I compute the clusters for the explorer tiles. I've added again on `master`.
