### ISSUE TITLE
Strava download fails

### ISSUE THREAD

**Issue by cs42** [martin-ueding/geo-activity-playground#66]
With version 0.14 the Strava download fails for me. Started with an empty playground directory using the `config.toml` from 0.13.

```
Traceback (most recent call last):
  File "/srv/gap/bin/geo-activity-playground", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/srv/gap/lib/python3.11/site-packages/geo_activity_playground/__main__.py", line 89, in main
    options.func(options)
  File "/srv/gap/lib/python3.11/site-packages/geo_activity_playground/__main__.py", line 64, in <lambda>
    make_activity_repository(options.basedir),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/gap/lib/python3.11/site-packages/geo_activity_playground/__main__.py", line 100, in make_activity_repository
    import_from_strava_api()
  File "/srv/gap/lib/python3.11/site-packages/geo_activity_playground/importers/strava_api.py", line 96, in import_from_strava_api
    client = Client(access_token=get_current_access_token())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/gap/lib/python3.11/site-packages/geo_activity_playground/importers/strava_api.py", line 53, in get_current_access_token
    token_response = client.exchange_code_for_token(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/gap/lib/python3.11/site-packages/stravalib/client.py", line 203, in exchange_code_for_token
    return self.protocol.exchange_code_for_token(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/gap/lib/python3.11/site-packages/stravalib/protocol.py", line 179, in exchange_code_for_token
    response = self._request(
               ^^^^^^^^^^^^^^
  File "/srv/gap/lib/python3.11/site-packages/stravalib/protocol.py", line 320, in _request
    self._handle_protocol_error(raw)
  File "/srv/gap/lib/python3.11/site-packages/stravalib/protocol.py", line 371, in _handle_protocol_error
    raise exc.Fault(msg, response=response)
stravalib.exc.Fault: 400 Client Error: Bad Request [Bad Request: [{'resource': 'AuthorizationCode', 'field': 'code', 'code': 'invalid'}]]
```

**Comment by martin-ueding** [comment]
The problem here is that Strava only allows to use the token you obtained exactly once to get the access and refresh token. Those are saved in the `Cache` directory. You need to re-authenticate with Strava and update your config file when you delete the cache.

I didn't of this before, so perhaps we can add something to the documentation.

**Comment by cs42** [comment]
Thanks, that's it.
