### ISSUE TITLE
possibly misleading help/documentation and dependencies

### ISSUE THREAD

**Issue by alexander-klump** [martin-ueding/geo-activity-playground#68]
I just wanted to test this nice program and tried to set it up quickly on ubuntu 22.04.3 in a virtualbox. Here is what hindered me:

1. I used the installation via pip: 
`sudo apt install pip`
`pip install --user geo-activity-playground`
After setting the PATH, closing the terminal wasn't enough, logout/login did it for me.
3. I already had a Playground directory with an Activities folder in it. Since the geo-activity-playground --help command showed me the --basedir flag, and there was this sentence "You have set up a playground with either activity files or the Strava API." in the "Starting the Webserver" section, I thought one had to give the path of the Activities folder as an argument to the basedir flag:
`geo-activity-playground --basedir=/home/Documents/Playground`
This produced only another help message. (So what exactly does this command do? See point 8. for a follow-up question.) Finally, reading ahead the sentence "`geo-activity-playground serve` if you are in the playground directory and have installed a stable version." in the "Starting The Webserver" section, made me trying `geo-activity-playground serve` in the Playground folder.
4.  This brought me to the following:
```
2023-12-12 22:45:52 geo_activity_playground.core.cache_migrations INFO Apply cache migration if needed …
2023-12-12 22:45:52 geo_activity_playground.core.cache_migrations INFO Applying cache migration delete_activities_per_tile …
2023-12-12 22:45:52 geo_activity_playground.core.config WARNING Missing a config, some features might be missing.
Traceback (most recent call last):
  File "/home/alexander/.local/bin/geo-activity-playground", line 8, in <module>
    sys.exit(main())
  File "/home/alexander/.local/lib/python3.10/site-packages/geo_activity_playground/__main__.py", line 89, in main
    options.func(options)
  File "/home/alexander/.local/lib/python3.10/site-packages/geo_activity_playground/__main__.py", line 64, in <lambda>
    make_activity_repository(options.basedir),
  File "/home/alexander/.local/lib/python3.10/site-packages/geo_activity_playground/__main__.py", line 101, in make_activity_repository
    repository = ActivityRepository()
  File "/home/alexander/.local/lib/python3.10/site-packages/geo_activity_playground/core/activities.py", line 41, in __init__
    self.meta = pd.read_parquet("Cache/activities.parquet")
  File "/home/alexander/.local/lib/python3.10/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
  File "/home/alexander/.local/lib/python3.10/site-packages/pandas/io/parquet.py", line 265, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
  File "/home/alexander/.local/lib/python3.10/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
  File "/home/alexander/.local/lib/python3.10/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'Cache/activities.parquet'
```
5. This confused me because I was not aware that it is necessary to configure anything due to the "convention over configuration mantra" in the "configuration file" section. Finally, from "Create the file Playground/config.toml" in the "Using Strava API" section I deduced the question **is necessary to have a `config.toml` in the Playground directory?**  I found out that it is not necessary. The error can be solved by solving the next step:
6. After creating this config file, the next try of executing `geo-activity-playground serve` yielded:
```
2023-12-12 22:50:09 geo_activity_playground.core.cache_migrations INFO Apply cache migration if needed …
Parse activity files: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/alexander/.local/bin/geo-activity-playground", line 8, in <module>
    sys.exit(main())
  File "/home/alexander/.local/lib/python3.10/site-packages/geo_activity_playground/__main__.py", line 89, in main
    options.func(options)
  File "/home/alexander/.local/lib/python3.10/site-packages/geo_activity_playground/__main__.py", line 64, in <lambda>
    make_activity_repository(options.basedir),
  File "/home/alexander/.local/lib/python3.10/site-packages/geo_activity_playground/__main__.py", line 97, in make_activity_repository
    import_from_directory()
  File "/home/alexander/.local/lib/python3.10/site-packages/geo_activity_playground/importers/directory.py", line 106, in import_from_directory
    merged.sort_values("start", inplace=True)
  File "/home/alexander/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 6944, in sort_values
    k = self._get_label_or_level_values(by[0], axis=axis)
  File "/home/alexander/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 1844, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'start'
```
which occured due to the fact that my Activities folder was simply empty. Thus **is it necessary to have at least one (gpx|fit|tcx)-file?**
7. After getting at least one .gpx file at hand into the Activities folder the webserver started, but trying to acces localhost:5000 in my browser ended up in "Internal Server Error" and throwing the following error:
```
2023-12-12 22:54:16 py.warnings WARNING /home/alexander/.local/lib/python3.10/site-packages/altair/utils/core.py:230: UserWarning: I don't know how to infer vegalite type from 'empty'.  Defaulting to nominal.
  warnings.warn(
2023-12-12 22:54:17 geo_activity_playground.webui.app ERROR Exception on / [GET]
Traceback (most recent call last):
  File "/home/alexander/.local/lib/python3.10/site-packages/altair/utils/_importers.py", line 15, in import_vegafusion
    import vegafusion as vf  # type: ignore
  File "/home/alexander/.local/lib/python3.10/site-packages/vegafusion/__init__.py", line 1, in <module>
    from .runtime import runtime
  File "/home/alexander/.local/lib/python3.10/site-packages/vegafusion/runtime.py", line 6, in <module>
    from .dataset import SqlDataset, DataFrameDataset
  File "/home/alexander/.local/lib/python3.10/site-packages/vegafusion/dataset/__init__.py", line 2, in <module>
    from .dataframe import DataFrameDataset, DataFrameOperationNotSupportedError
  File "/home/alexander/.local/lib/python3.10/site-packages/vegafusion/dataset/dataframe.py", line 3, in <module>
    from vegafusion.proto.datafusion_pb2 import LogicalExprNode
  File "/home/alexander/.local/lib/python3.10/site-packages/vegafusion/proto/datafusion_pb2.py", line 8, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/usr/lib/python3/dist-packages/google/protobuf/internal/__init__.py)

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/alexander/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexander/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexander/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexander/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/alexander/.local/lib/python3.10/site-packages/geo_activity_playground/webui/app.py", line 34, in index
    return render_template("index.html.j2", **entry_controller.render())
  File "/home/alexander/.local/lib/python3.10/site-packages/geo_activity_playground/webui/entry_controller.py", line 19, in render
    "distance_last_30_days_plot": distance_last_30_days_meta_plot(
  File "/home/alexander/.local/lib/python3.10/site-packages/geo_activity_playground/webui/entry_controller.py", line 41, in distance_last_30_days_meta_plot
    alt.Chart(
  File "/home/alexander/.local/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 1042, in to_json
    spec = self.to_dict(
  File "/home/alexander/.local/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 2975, in to_dict
    return super().to_dict(
  File "/home/alexander/.local/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 993, in to_dict
    return _compile_with_vegafusion(vegalite_spec)
  File "/home/alexander/.local/lib/python3.10/site-packages/altair/utils/_vegafusion_data.py", line 149, in compile_with_vegafusion
    vf = import_vegafusion()
  File "/home/alexander/.local/lib/python3.10/site-packages/altair/utils/_importers.py", line 19, in import_vegafusion
    raise ImportError(
ImportError: The "vegafusion" data transformer and chart.transformed_data feature requires
version 1.4.0 or greater of the 'vegafusion-python-embed' and 'vegafusion' packages.
These can be installed with pip using:
    pip install "vegafusion[embed]>=1.4.0"
Or with conda using:
    conda install -c conda-forge "vegafusion-python-embed>=1.4.0" "vegafusion>=1.4.0"
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/usr/lib/python3/dist-packages/google/protobuf/internal/__init__.py)
```
I could solve this by running `pip install "vegafusion[embed]>=1.4.0"` and `pip install --upgrade protobuf`
8. It runs now and I can access the webserver. What is odd now, is that it displays my test .gpx file twice. During my issues with step 3. I thought the problem would be that I chose as a Playground a folder which was a shared folder of my virtualbox with my host system, so I renamed the .gpx file to test.gpx and moved everything to a ordinary folder. (But I already ran `geo-activity-playground --basedir=/home/Documents/SharedFolder/Playground`) How can I remove the old Playground files?

**Comment by martin-ueding** [comment]
Thank you for the detailed report, this is very helpful! I'm grateful that you took the time to try again and again.

I've updated the documentation a bit, adding a sentence that it is required to have at least one activity file there. Now that I read yours and other's reports, it is plausible to assume that one starts the thing and upload the files in the web interface like one would do with Strava.

Also there is now an error message in the upcoming version 0.15.0 when there are no activity files. This should it make more helpful.

I am a bit puzzled by the last error that you got. I explicitly got those dependencies listed:

```toml
vegafusion = "^1.4.3"
vegafusion-python-embed = "^1.4.3"
```

I am not sure why these were not picked up correctly. I would assume that the problem really was the outdated protobuf installation. So one of the dependencies doesn't specify a minimum version properly.

**Comment by martin-ueding** [comment]
I assume the 👍🏻 means that this fixes the issue for you, therefore I'll close it. Feel free to reopen.
