### ISSUE TITLE
Error  "Object of type Series is not JSON serializable" for tile pages

### ISSUE THREAD

**Issue by Natenom** [martin-ueding/geo-activity-playground#75]
```
127.0.0.1 - - [22/Dec/2023 18:41:27] "GET / HTTP/1.1" 200 -
[2023-12-22 18:41:30,273] ERROR in app: Exception on /explorer/14 [GET]
Traceback (most recent call last):
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my/src/github/geo-activity-playground/geo_activity_playground/webui/app.py", line 63, in explorer
    "explorer.html.j2", **explorer_controller.render(int(zoom))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my/src/github/geo-activity-playground/geo_activity_playground/webui/explorer_controller.py", line 193, in render
    explored = get_three_color_tiles(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my/src/github/geo-activity-playground/geo_activity_playground/webui/explorer_controller.py", line 126, in get_three_color_tiles
    "explored_geojson": geojson.dumps(
                        ^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/geojson/codec.py", line 31, in dumps
    return json.dumps(to_mapping(obj),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/geojson/codec.py", line 14, in default
    return geojson.factory.GeoJSON.to_instance(obj) # NOQA
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/geojson/base.py", line 99, in to_instance
    mapping = to_mapping(ob)
              ^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/geojson/mapping.py", line 39, in to_mapping
    return json.loads(json.dumps(obj))
                      ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Series is not JSON serializable
127.0.0.1 - - [22/Dec/2023 18:41:30] "GET /explorer/14 HTTP/1.1" 500 -
```

**Comment by martin-ueding** [comment]
Kannst du es nochmal mit der neusten Version probieren? Ich lasse jetzt einmal das ganze Teil ausgeben, darin sollte dann das Problem zu finden sein. In der Ausgabe wird wahrscheinlich irgendwas mit `Series` stehen. Kannst du da einmal schauen, ob du etwas findest?

**Comment by Natenom** [comment]
Mit der aktuellen Version und dem Parameter `--loglevel debug`:

```
2023-12-22 19:12:15 geo_activity_playground.webui.app ERROR Exception on /explorer/14 [GET]
Traceback (most recent call last):
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my/src/github/geo-activity-playground/geo_activity_playground/webui/app.py", line 63, in explorer
    "explorer.html.j2", **explorer_controller.render(int(zoom))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my/src/github/geo-activity-playground/geo_activity_playground/webui/explorer_controller.py", line 193, in render
    explored = get_three_color_tiles(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my/src/github/geo-activity-playground/geo_activity_playground/webui/explorer_controller.py", line 131, in get_three_color_tiles
    explored_geojson = geojson.dumps(feature_collection)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/geojson/codec.py", line 31, in dumps
    return json.dumps(to_mapping(obj),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/geojson/codec.py", line 14, in default
    return geojson.factory.GeoJSON.to_instance(obj) # NOQA
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/geojson/base.py", line 99, in to_instance
    mapping = to_mapping(ob)
              ^^^^^^^^^^^^^^
  File "/home/me/.cache/pypoetry/virtualenvs/geo-activity-playground-SZxD7HkL-py3.11/lib/python3.11/site-packages/geojson/mapping.py", line 39, in to_mapping
    return json.loads(json.dumps(obj))
                      ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Series is not JSON serializable
2023-12-22 19:12:15 werkzeug INFO 127.0.0.1 - - [22/Dec/2023 19:12:15] "GET /explorer/14 HTTP/1.1" 500 -

```

**Comment by Natenom** [comment]
Oh, ich sehe, was du meinst, du meinst das oben drüber :)

```
Embellish time series data: 0it [00:00, ?it/s]
Embellish time series data: 0it [00:00, ?it/s]
[…]
 * Running on http://127.0.0.1:5000
2023-12-22 19:20:00 werkzeug INFO [33mPress CTRL+C to quit[0m
2023-12-22 19:20:04 geo_activity_playground.explorer.grid_file INFO Generate data for explorer tile map …
2023-12-22 19:20:04 geo_activity_playground.explorer.grid_file ERROR Encountered TypeError while building GeoJSON: e=TypeError('Object of type Series is not JSON serializable')
2023-12-22 19:20:04 geo_activity_playground.explorer.grid_file ERROR tile_dict = {(8591, 5641): {'first_activity_id': '3280298792219127921', 'first_activity_name': index
```

Und dann gibts noch an ein paar Stellen Fehler bei Series in Bezug auf die .png-Dateien im Verzeichnis.

**Comment by martin-ueding** [comment]
Kannst du mir von der Zeile mit `ERROR tile_dict` mehr schicken? Es fängt da gerade an interessant zu werden mit `index`, das sollte da nicht sein. Idealerweise so weit bis das nächste Tupel wie `(8591, 5641)` kommt.

**Comment by Natenom** [comment]
Nach dieser Zeile kommen ca. 3000 Zeilen mit Infos zu verschiedenen Dateien. Und das ist die einzige Zeile mit `tile_dict` im ganzen Log.

**Comment by martin-ueding** [comment]
Ja, das ist der Plan. Irgendwo da ist das Problem drin. Das `tile_dict` müsste ziemlich groß sein. Wenn du mir ein bisschen mehr davon geben könntest, kann ich vielleicht herausfinden, warum dort etwas drin ist, was da nicht drin sein sollte.

**Comment by Natenom** [comment]
Ok, hier mal die ersten Zeilen davon, da sind halt alle Dateinamen drin, die teilweise persönliche Daten enthalten, daher bin ich da lieber vorsichtig:

```
[…]
3280298792219127921    file1
3280298792219127921    file1
Name: name, dtype: object, 'last_activity_id': '612970775510671141', 'last_activity_name': index
612970775510671141    file2
612970775510671141    file2
Name: name, dtype: object, 'first_age_days': 3371, 'first_age_color': '#0d0887', 'last_age_days': 28, 'last_age_color': '#f5e926', 'cluster': True, 'color': '#1f77b4', 'first_visit': '2014-09-29', 'last_visit': '2023-11-24', 'num_visits': 398, 'square': False, 'this_cluster_size': 56}, (8591, 5640): {'first_activity_id': '3280298792219127921', 'first_activity_name': index
3280298792219127921    file1
3280298792219127921    file1
Name: name, dtype: object, 'last_activity_id': '3424593700895032738', 'last_activity_name': index
3424593700895032738    file3
3424593700895032738    file3
Name: name, dtype: object, 'first_age_days': 3371, 'first_age_color': '#0d0887', 'last_age_days': 9, 'last_age_color': '#f1f426', 'cluster': True, 'color': '#1f77b4', 'first_visit': '2014-09-29', 'last_visit': '2023-12-13', 'num_visits': 628, 'square': False, 'this_cluster_size': 56}, (8586, 5633): {'first_activity_id': '1112321838369727914', 'first_activity_name': index
1112321838369727914    2353448697
1112321838369727914    2353448697
Name: name, dtype: object, 'last_activity_id': '206940274799107602', 'last_activity_name': index
206940274799107602    file4
206940274799107602    file4
Name: name, dtype: object, 'first_age_days': 1746, 'first_age_color': '#0d0887', 'last_age_days': 11, 'last_age_color': '#f1f426', 'cluster': True, 'color': '#1f77b4', 'first_visit': '2019-03-12', 'last_visit': '2023-12-11', 'num_visits': 288, 'square': False, 'this_cluster_size': 56}, (8587, 5633): {'first_activity_id': '3737422730415688719', 'first_activity_name': index
3737422730415688719    file5
3737422730415688719    file5
Name: name, dtype: object, 'last_activity_id': '206940274799107602', 'last_activity_name': index
206940274799107602    file4
206940274799107602    file4
Name: name, dtype: object, 'first_age_days': 2687, 'first_age_color': '#0d0887', 'last_age_days': 11, 'last_age_color': '#f1f426', 'cluster': True, 'color': '#1f77b4', 'first_visit': '2016-08-13', 'last_visit': '2023-12-11', 'num_visits': 303, 'square': False, 'this_cluster_size': 56}, (8587, 5632): {'first_activity_id': '3737422730415688719', 'first_activity_name': index
3737422730415688719    file5
3737422730415688719    file5
Name: name, dtype: object, 'last_activity_id': '2389335035256205298', 'last_activity_name': index
2389335035256205298    file6
2389335035256205298    file6
Name: name, dtype: object, 'first_age_days': 2687, 'first_age_color': '#0d0887', 'last_age_days': 32, 'last_age_color': '#f6e626', 'cluster': False, 'color': '#303030', 'first_visit': '2016-08-13', 'last_visit': '2023-11-20', 'num_visits': 79, 'square': False}, (8588, 5632): {'first_activity_id': '1877840762051332419', 'first_activity_name': index
1877840762051332419    2623252881
1877840762051332419    2623252881
[…]
```

**Comment by martin-ueding** [comment]
Danke, das hilft schon einmal. Ich verstehe nicht ganz, wie das passieren kann. Aber ich untersuche das demnächst mal.

**Comment by Natenom** [comment]
Ich hab jetzt mal den Cache gelöscht und in die Activities nur die .fit-Dateien vom Wahoo eingefügt und da gibt es das Problem nicht. Später werde ich mal versuchen, das einzugrenzen, damit ich dir eine verursachende Datei schicken kann.

**Comment by Natenom** [comment]
Ich hab jetzt versucht, die Dateien einzugrenzen und alle exisiterenden Unterverzeichnisse in eigenen basedirs einzubinden. Und zuletzt hab ich nochmal alle eingebunden, hätte also auch einfach nur den Cache löschen können.

Nu geht es.

**Comment by martin-ueding** [comment]
Merkwürdig. Dann mache ich hier einmal zu. Wenn es nochmal auftritt, bitte wieder aufmachen.
