### ISSUE TITLE
Error with `.fit` activities with NoneType subsport

### ISSUE THREAD

**Issue by antonmosich** [martin-ueding/geo-activity-playground#84]
I just tried out running 0.17.1 and encountered the following error:
```
Parse activity files:   2%|█                                                       | 203/11221 [00:08<02:02, 90.08it/s]2024-01-13 12:28:25 geo_activity_playground.importers.directory ERROR Encountered a problem with path=PosixPath('Activities/filename.fit'), see details below.
Parse activity files:   2%|█                                                       | 207/11221 [00:08<07:30, 24.47it/s]
Traceback (most recent call last):
  File "/nix/store/88a9n13fznshkf45x2a9sd5fcy27vr6p-geo-activity-playground-0.17.1/bin/.geo-activity-playground-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/88a9n13fznshkf45x2a9sd5fcy27vr6p-geo-activity-playground-0.17.1/lib/python3.11/site-packages/geo_activity_playground/__main__.py", line 95, in main
    options.func(options)
  File "/nix/store/88a9n13fznshkf45x2a9sd5fcy27vr6p-geo-activity-playground-0.17.1/lib/python3.11/site-packages/geo_activity_playground/__main__.py", line 70, in <lambda>
    make_activity_repository(options.basedir),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/88a9n13fznshkf45x2a9sd5fcy27vr6p-geo-activity-playground-0.17.1/lib/python3.11/site-packages/geo_activity_playground/__main__.py", line 103, in make_activity_repository
    import_from_directory()
  File "/nix/store/88a9n13fznshkf45x2a9sd5fcy27vr6p-geo-activity-playground-0.17.1/lib/python3.11/site-packages/geo_activity_playground/importers/directory.py", line 41, in import_from_directory
    activity_meta_from_file, timeseries = read_activity(path)
                                          ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/88a9n13fznshkf45x2a9sd5fcy27vr6p-geo-activity-playground-0.17.1/lib/python3.11/site-packages/geo_activity_playground/core/activity_parsers.py", line 44, in read_activity
    metadata, timeseries = read_fit_activity(path, opener)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/88a9n13fznshkf45x2a9sd5fcy27vr6p-geo-activity-playground-0.17.1/lib/python3.11/site-packages/geo_activity_playground/core/activity_parsers.py", line 175, in read_fit_activity
    metadata["kind"] += " " + values["sub_sport"]
                        ~~~~^~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```

I tried packaging geo-activity-playground in nix, so that's why the paths for the files are the way they are, but this _shouldn't_ be causing this issue.
I can send you the activity file via some other channel if you want that.

**Comment by martin-ueding** [comment]
It's a bug I've introduced with version 0.17.1. I've fixed it in the just released 0.17.2.

**Comment by antonmosich** [comment]
Thanks for fixing, now it errors on another file, where the sub_sport seems to be an integer with essentially the same error.

**Comment by martin-ueding** [comment]
That's annoying. The FIT documentation said something about it being an enumeration type. For my files from the Garmin Venu Sq watch it is a string. Either way, I now force it to be a string. It could be that in your case there are just boring numbers. Try out version 0.17.5, that should at least import everything.

If you'd like me to take a look at your file, you could send it to <mu@martin-ueding.de> and I'll try to import it on my system.

**Comment by martin-ueding** [comment]
I've managed to import one of your files. The other files doesn't contain any FIT frames with geo data, as I've written in the e-mail.
